version: '3.7'
services:

  php:
    build: 
      context: ./
      dockerfile: dockerfile
    ports:
     - "9000:9000"
    volumes:
     - ./public/:/var/www/html
     - ./public/:/code/
    image: "php:7.3.1-fpm"

  nginx:
    image: "nginx:latest"
    ports: 
     - "80:80"
    volumes:
     - ./public/:/etc/nginx/html
     - ./config/nginx.conf:/etc/nginx/conf.d/default.conf

  db:
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
     - ./db/:/var/lib/mysql
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_DATABASE: "db"
